# Generated by Django 4.0.1 on 2022-01-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_categoryjoin_product_categorysubcategory_id'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategorySubCatergory',
            new_name='CategorySubCategory',
        ),
    ]
