# Generated by Django 4.0.1 on 2022-01-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='img_url',
            field=models.URLField(default='null', max_length=1000),
            preserve_default=False,
        ),
    ]
