# Generated by Django 4.0.1 on 2022-01-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productgroup_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
