# Generated by Django 4.0.1 on 2022-01-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_categoryjoin_product_categorysubcategory_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categorysubcategory_id',
            new_name='categorysubcategory',
        ),
    ]
