# Generated by Django 4.0.1 on 2022-01-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img_url',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='productgroup',
            old_name='img_url',
            new_name='image_url',
        ),
    ]
